version: 43.0.9
pageUuid: f5a89d12-8df9-11ec-95c6-8f76e4f1247c
appTemplate:
  appThemeId: -1
  inAppRetoolPillAppearance: HIDE_MENU
  customDocumentTitle: samfitz.xyz
  rootScreen: null
  customDocumentTitleEnabled: true
  preloadedAppJSLinks:
    array:
      - https://cdn.skypack.dev/three@0.138.3
  version: 2.83.28
